### ISSUE TITLE
Error when searching with limetorrents

### ISSUE THREAD

**Issue by scambra** [barbequesauce/Watcher3#44]
I get this error for limetorrents indexer:

ERROR [2019-10-02 19:59:32,559] core.providers.torrent_modules.limetorrents.search.30: LimeTorrent search failed.
Traceback (most recent call last):
  File "/app/watcher/lib/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/app/watcher/lib/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/app/watcher/lib/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/app/watcher/lib/requests/packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/app/watcher/lib/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
lib.requests.packages.urllib3.exceptions.NewConnectionError: <lib.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x74101c50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/watcher/lib/requests/adapters.py", line 436, in send
    timeout=timeout
  File "/app/watcher/lib/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/app/watcher/lib/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
lib.requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.limetorrents.cc', port=443): Max retries exceeded with url: /searchrss/la%20oveja%20shaun%20la%20peli%CC%81cula%202015 (Caused by NewConnectionError('<lib.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x74101c50>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/watcher/core/providers/torrent_modules/limetorrents.py", line 21, in search
    response = Url.open(url).text
  File "/app/watcher/core/helpers.py", line 90, in open
    r = requests.get(url, **kwargs)
  File "/app/watcher/lib/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/app/watcher/lib/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/watcher/lib/requests/sessions.py", line 497, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/watcher/lib/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/app/watcher/lib/requests/adapters.py", line 500, in send
    raise ConnectionError(e, request=request)
lib.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.limetorrents.cc', port=443): Max retries exceeded with url: /searchrss/la%20oveja%20shaun%20la%20peli%CC%81cula%202015 (Caused by NewConnectionError('<lib.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x74101c50>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by ellnic** [comment]
I think there are issues with torrents across the board. I was looking at it the other day, but have been so busy I haven’t managed to collate findings and open issues. As far as I can tell, watcher is also unable to search TPB properly (results that are known to exist are not found by watcher) and Zooqle magnets throw an error about path information yet the magnet does exist.

**Comment by scambra** [comment]
I'm just adding here so I remember later to debug them. Also adding other issues or features I want, as reminder, I have intention to work on them and submit PRs.

**Comment by barbequesauce** [comment]
Interestingly I have no problem with transmission plus label:Watcher plus indexer: PtP

**Comment by ellnic** [comment]
I'm not sure if this is resolved. I am only getting results from rarbg and zooqle. As mentioned here: https://github.com/barbequesauce/Watcher3/issues/75

All others give no results at all. Is this not what you are seeing @scambra @barbequesauce?

**Comment by scambra** [comment]
I'm getting results from this tracker. Have you checked if you get results but they are rejected?

**Comment by ellnic** [comment]
I have double checked using the top 3 films from this list: https://www.imdb.com/search/title/?groups=top_250&sort=user_rating

I only ever get results from rarbg or zooqle. 

I run all through a VPN, could this be related?

**Comment by scambra** [comment]
I don't know, I had issue with some web sites because my ISP blocked it, and DNS returned 127.0.0.1 for them. I didn't realize until I tried to open url used by watcher in my browser, or with curl in terminal:

curl https://www.limetorrents.info/searchrss/The%20Shawshank%20Redemption%201994
curl https://www.thepiratebay.org/search/tt0111161/0/99/200
curl https://www.torrentdownloads.me/rss.xml?type=search&search=The%20Shawshank%20Redemption%201994
curl https://www.torrentz2.eu/feed?f=The%20Shawshank%20Redemption%201994
curl https://yts.lt/api/v2/list_movies.json?limit=1&query_term=tt0111161

I can get results for all of them

**Comment by ellnic** [comment]
Hrm. Ok, I will try this tomorrow from my end and report back.

**Comment by ellnic** [comment]
I get:

```
bash-4.4# curl https://www.limetorrents.info/searchrss/The%20Shawshank%20Redemption%201994/
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.limetorrents.info:443 

bash-4.4# curl https://www.thepiratebay.org/search/tt0111161/0/99/200
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

bash-4.4# curl 'https://www.torrentdownloads.me/rss.xml?type=search&search=The%20Shawshank%20Redemption%201994'
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

bash-4.4# curl https://www.torrentz2.eu/feed?f=The%20Shawshank%20Redemption%201994
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.torrentz2.eu:443 

bash-4.4# curl 'https://yts.lt/api/v2/list_movies.json?limit=1&query_term=tt0111161'
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to yts.lt:443 
```

But I can connect via Midori that uses VPN. 

I use the binhex/arch-delugevpn docker. It uses Privoxy which I route other apps through.

**Comment by ellnic** [comment]
Apologies, this appears to be a privoxy issue. If I exec into the vpn container, the curls work fine: 

```
curl 'https://yts.lt/api/v2/list_movies.json?limit=1&query_term=tt0111161'
{"status":"ok","status_message":"Query was successful","data":{"movie_count":1,"limit":1,"page_number":1,"movies":[{"id":3709,"url":"https:\/\/yts.lt\/movie\/the-shawshank-redemption-1994","imdb_code":"tt0111161","title":"The Shawshank Redemption","title_english":"The Shawshank Redemption","title_long":"The Shawshank Redemption (1994)","slug":"the-shawshank-redemption-1994","year":1994,"rating":9.3,"runtime":142,"genres":["Action","Crime","Drama"],"summary":"Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.","description_full":"Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.","synopsis":"Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.","yt_trailer_code":"K_tLp7T6U1c","language":"English","mpa_rating":"R","background_image":"https:\/\/yts.lt\/assets\/images\/movies\/The_Shawshank_Redemption_1994\/background.jpg","background_image_original":"https:\/\/yts.lt\/assets\/images\/movies\/The_Shawshank_Redemption_1994\/background.jpg","small_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/The_Shawshank_Redemption_1994\/small-cover.jpg","medium_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/The_Shawshank_Redemption_1994\/medium-cover.jpg","large_cover_image":"https:\/\/yts.lt\/assets\/images\/movies\/The_Shawshank_Redemption_1994\/large-cover.jpg","state":"ok","torrents":[{"url":"https:\/\/yts.lt\/torrent\/download\/AC418DB33FA5CEA4FAB11BC58008FE08F291C9BE","hash":"AC418DB33FA5CEA4FAB11BC58008FE08F291C9BE","quality":"720p","type":"bluray","seeds":470,"peers":108,"size":"848.96 MB","size_bytes":890199081,"date_uploaded":"2015-11-01 03:20:23","date_uploaded_unix":1446344423},{"url":"https:\/\/yts.lt\/torrent\/download\/E0D00667650ABA9EE05AACBBBD8B55EA8A51F534","hash":"E0D00667650ABA9EE05AACBBBD8B55EA8A51F534","quality":"1080p","type":"bluray","seeds":216,"peers":54,"size":"1.60 GB","size_bytes":1717986918,"date_uploaded":"2015-11-01 03:20:25","date_uploaded_unix":1446344425}],"date_uploaded":"2015-11-01 03:20:23","date_uploaded_unix":1446344423}]},"@meta":{"server_time":1574853720,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}
```

I will look at Privoxy and see what I can find.

**Comment by ellnic** [comment]
Ok, it's nothing to do with privoxy. After trying may things, it occured to me that only the indexer requests are going via privoxy, not the entire container.

From within my watcher container, I checked first with:

`curl ipinfo.io` 

and got my own IP details, then again with the indexer curls, and got the same error. So this isn't anything to do with privoxy.

Not sure why this works within the VPN container and not the Watcher container. Do you have any insight @scambra?

**Comment by scambra** [comment]
It can be an issue with ssl. You can try with wget 'url' -O -, I didn't tried with curl inside docker instance because my instance doesn't have curl installed, but I don't route traffic through vpn, so running on raspberry gives same result.

Do you have any error in log? Watcher could have same ssl issue.

**Comment by ellnic** [comment]
Wget from watcher container: 

`bash-4.4# wget 'https://yts.lt/api/v2/list_movies.json?limit=1&query_term=tt0111161' -O -
Connecting to yts.lt (104.27.217.4:443)
ssl_client: yts.lt: handshake failed: Connection reset by peer
wget: error getting response: Connection reset by peer`

so I also checked from Sickgear:

```
/ # wget 'https://yts.lt/api/v2/list_movies.json?limit=1&query_term=tt0111161' -
O - 
--2019-11-27 17:32:35--  https://yts.lt/api/v2/list_movies.json?limit=1&query_term=tt0111161
Resolving yts.lt... 104.27.217.4, 104.27.216.4
Connecting to yts.lt|104.27.217.4|:443... connected.
Unable to establish SSL connection.
```

and from VPN container:

`` "status":"ok","status_message":"Query was successful","data" `` [truncated]

So I fired up a Watcher instance outside of docker and connected to privoxy and I only get zooqle results.

I noticed this in the log: 

`` WARNING [2019-11-27 17:38:56,466] core.proxy.create.71: HTTP-only proxy. HTTPS traffic will not be tunneled through proxy. ``

Is this an error or something that can be worked around? I don't think the container I use has an https option.

**Comment by ellnic** [comment]
More info [this is probably worthy of a new issue at this point] 

I fired up another well used proxy container: haugene/transmission-openvpn and it's working fine via Midori, and I get Zooqle results, but this time no rarbg.

Errors: https://pastebin.com/raw/byphXbmk

So you may be right about an ssl issue, unless I am doing something very wrong with my dockers - which is not an impossibility. I can curl and wget https just fine from other containers though, and Midori is accessing https site just fine.

**Comment by scambra** [comment]
If I understand right, you have proxy enabled in watcher, but you have setup proxy as http://..., so watcher reports https traffic won't use proxy. The only url without https in watcher is in limetorrents indexer, but it redirects to https too.

I have tried with 2 instances:
* one based on lsiobase/alpine:3.8, using libressl 2.7.5
```
# apk list|grep ssl
libressl2.7-libcrypto-2.7.5-r0 armhf {libressl} (custom) [installed]
libressl2.7-libtls-2.7.5-r0 armhf {libressl} (custom) [installed]
ssl_client-1.28.4-r3 armhf {busybox} (GPL-2.0) [installed]
libressl2.7-libssl-2.7.5-r0 armhf {libressl} (custom) [installed]
```
* another based on lsiobase/python:3.10, using openssl 1.1.1c
```
# apk list |grep ssl
libssl1.1-1.1.1c-r0 armv7 {openssl} (OpenSSL) [installed]
ssl_client-1.30.1-r2 armv7 {busybox} (GPL-2.0) [installed]
openssl-1.1.1c-r0 armv7 {openssl} (OpenSSL) [installed]
libcrypto1.1-1.1.1c-r0 armv7 {openssl} (OpenSSL) [installed]
```

Which ssl libraries do you have in docker instance? If they are updated, maybe it's a bug with urllib3 python library, I think watcher has a copy of library, v1.20, and I found a similar bug report in debian, fixed in 1.22. Or we need to update requests library, because urllib3 is inside lib/requests/packages

**Comment by ellnic** [comment]
Yes that's the error it reports, but then zooqle and rarbg work - not limetorrents, so there is no logic to it. It does seem to point towards a bug. 

I based it on alpine 3.8 too, so my output is identical to your LSIO one:

`libressl2.7-libcrypto-2.7.5-r0 x86_64 {libressl} (custom) [installed]
libressl2.7-libtls-2.7.5-r0 x86_64 {libressl} (custom) [installed]
ssl_client-1.28.4-r3 x86_64 {busybox} (GPL-2.0) [installed]
libressl2.7-libssl-2.7.5-r0 x86_64 {libressl} (custom) [installed]
`

I could change the Alpine base and see if a newer version helps? I think Alpine are on 3.10 now.

The libressl version is still [2.7.5-r0](https://pkgs.alpinelinux.org/packages?name=libressl&branch=v3.10) but the ssl_client is [1.30.1-r3
](https://pkgs.alpinelinux.org/packages?name=ssl_client&branch=v3.10)

**Comment by ellnic** [comment]
@scambra  I have moved the image to Alpine 3.10.3 but the same errors persist.

**Comment by scambra** [comment]
I'm thinking again, if wget fails with ssl error, it must be something in the system. Try to open an issue in alpine issue tracker, because wget should work for yts.lt or limetorrents.info, as it works for zooqle.com. I have updated my instance to lsiobase/alpine:3.10 and it still works, with openssl instead of libressl. I don't use plain alpine image, because I based my dockerfile in old linuxserver dockerfile for watcher, maybe something added by lsiobase/alpine is fixing the ssl issue.

**Comment by ellnic** [comment]
It's not Alpine related, because I can get the issue if I run from the terminal on the host: 

```
ssl.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)
raise ssl.SSLError('bad handshake: %r' % e)
File "/home/ellnic/Desktop/Watcher3-master/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 443, in wrap_socket
return context.wrap_socket(sock, server_hostname=server_hostname)
File "/home/ellnic/Desktop/Watcher3-master/lib/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
ssl_context=context)
File "/home/ellnic/Desktop/Watcher3-master/lib/requests/packages/urllib3/connection.py", line 326, in connect
conn.connect()
File "/home/ellnic/Desktop/Watcher3-master/lib/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
self._validate_conn(conn)
File "/home/ellnic/Desktop/Watcher3-master/lib/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
chunked=chunked)
File "/home/ellnic/Desktop/Watcher3-master/lib/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
```

I'm thinking this is pointing back to Privoxy.

But if I check Sickgear, which also runs via Privoxy, I seem to be able to connect:

```
2019-11-29 10:26:26 INFO     RECENT-SEARCH :: [EZTV] :: 50 cache items in response from https://eztv.ag/page_1
2019-11-29 10:26:25 INFO     RECENT-SEARCH :: [Skytorrents] :: 25 cache items in response from https://skytorrents.lol/?category=show&sort=created&query=x264&page=2
2019-11-29 10:26:24 INFO     RECENT-SEARCH :: [Skytorrents] :: 25 cache items in response from https://skytorrents.lol/?category=show&sort=created&query=x264&page=
2019-11-29 10:26:24 INFO     RECENT-SEARCH :: [Zooqle] :: 24 cache items in response from https://zooqle.com/search?q=* category:Anime,TV %2Blang%3Aen&s=dt&v=t&sd=d
2019-11-29 10:26:22 INFO     RECENT-SEARCH :: [EZTV] :: 50 cache items in response from https://eztv.ag/page_0
2019-11-29 10:26:20 INFO     RECENT-SEARCH :: [TorLock] :: 100 cache items in response from https://www.torlock.com/television/1/added/desc.html
2019-11-29 10:26:19 INFO     RECENT-SEARCH :: [The Pirate Bay] :: 50 cache items in response from https://pirateproxy.ch/tv/latest/
2019-11-29 10:26:18 INFO     RECENT-SEARCH :: [MagnetDL] :: 80 cache items in response from http://www.magnetdl.com/download/tv/, http://www.magnetdl.com/download/tv/2
2019-11-29 10:26:17 INFO     RECENT-SEARCH :: [Nyaa] :: 75 cache items in response from https://www.nyaa.si/?f=0&c=1_0&q=
2019-11-29 10:26:15 INFO     RECENT-SEARCH :: [Snowfl] :: 5 cache items in response from https://snowfl.com/OxGAuKipiPsZOyLnezXAJoKyPnxrXqIAH/Q/BkF3bp52/0/DATE/24/0?_=1575023174788
2019-11-29 10:26:13 INFO     RECENT-SEARCH :: [TokyoToshokan] :: 150 cache items in response from https://tokyotosho.info/rss.php?filter=1
```
I'm going to open an issue on binhex's git, because I think this may be something more related to that.

**Comment by ellnic** [comment]
Yay! I have resolved this I think, by switching to socks5. Will test over the next few days.
